### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by phadej** [NorfairKing/typed-uuid#1]
on GHC-7.10.3 

```
src/Data/UUID/Typed.hs:8:8:
    Could not find module ‘Control.Monad.IO.Class’
    It is a member of the hidden package ‘transformers-0.5.2.0@9bQiiqEjk1m49Kq789uTsg’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.3.1@9rJIPUWhJU188HsU3MI2Gz’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.0.1@GitGv9ioSed42QPUlWYZZ0’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.0.2@8Q8SI6npdDdGmLNC130KUx’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.4.0@CBZP4azR07y8fwUbBRPPsd’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.3.0@8wFzMwpbjIBHuzBccd0QGa’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.4.3.0@9WrkpyzBdpxBTPjrNxQq7n’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.6.1@G8F8EDPhg2P450Lh8adEF’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.6.0@DMms1kYfaBn5c2kLzrfC8d’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.6.2@67ik8iQhEGy3GAZigAlz0V’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.0.0@8kADiMQKgyLI0714bFcRbA’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.1.0@4C2sUt3a0j31ceslTeCSjv’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.5.5.2@I3jfjDLbHOF4Fyi21cm3Cf’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘transformers-0.4.2.0@trans_GZTjP9K5WFq01xC9BAGQpF’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.

```

on GHC-8.2.2

```
src/Data/UUID/Typed.hs:91:55: error:
    • Variable not in scope:
        (<>) :: Either [Char] b0 -> Text -> Either Text (UUID a)
    • Perhaps you meant one of these:
        ‘<*>’ (imported from Prelude), ‘*>’ (imported from Prelude),
        ‘>>’ (imported from Prelude)
```

Please pay attention to older GHCs, or/and specify tested lower bounds.

**Comment by NorfairKing** [comment]
Djeesh, that's an age-old ghc version. What lower-bounds do you recommend? I'm starting to consider just not publishing my packages and have people only refer to them by git repo and revision. This whole churn is super tedious.

**Comment by phadej** [comment]
If you care only about stack LTS/nightly, than having `base >=4.12` / `base >=4.13` is perfectly fine. You don't need to support less than you test.

**Comment by NorfairKing** [comment]
Ok thanks! It doesn't help that `GHC-X.Y.Z` or `lts-X.YY` doesn't help me to figure out which base version that means. 

> EDIT: For the record GHC-8.2 is 2.5 years old.

Yeah I only meant to complain about 7.10.3 :)

**Comment by NorfairKing** [comment]
This package should really "just work" with any ghc version, because it's just a type with a phantom type parameter and basically nothing else. Why is it such a pain to get that right. And don't even get me started on setting up CI for it.

**Comment by phadej** [comment]
There's [`haskell-ci`](https://github.com/haskell-ci/haskell-ci), it's a breeze to setup CI with it. (maybe not the first time, and not for stack users, sorry).

https://www.stackage.org/lts-14.25 does list `base-4.12.0.0`, it's not that difficult. (Also trial and error works, if you specify too strict one at first).

You spend a lot of time finding bugs in others code, spend a fraction on devops of your packages :)

**Comment by NorfairKing** [comment]
Should be fixed in the latest version now.

**Comment by phadej** [comment]
Thanks.

FWIW, I have [blogged about compatibility packages](https://oleg.fi/gists/posts/2019-06-03-compat-packages.html), in particular [`base-compat`](https://hackage.haskell.org/package/base-compat) eases with changes in `base` / `Prelude`.

> The scope of base-compat is to provide functions available in later versions of base to a wider (older) range of compilers.
>
> One common at the time problem was <$> not in scope, due AMP. This kind of small problems are easily fixed with
>
>     import Prelude ()
>     import Prelude.Compat

And also `<>` nowadays, e.g.

**Comment by NorfairKing** [comment]
@phadej Thanks! I will consider using `base-compat` for libraries if I need them to work with a lot of ghc versions in the future.
